from app.db.base import Base
from app.models.company import Company
from app.models.user import User
from app.models.ticket import Ticket
from app.models.message import Message
from app.models.protocol import Protocol
from app.models.protocol_chunk import ProtocolChunk
from app.models.knowledge_gap import KnowledgeGap
from app.models.ticket_event import TicketEvent
